name: gcam
channels:
  - defaults
dependencies:
  - opencv
  - scikit-image
  - jupyter
  - matplotlib
  - tqdm
  - pytorch
  - cudatoolkit=10.1
  - torchvision
  - dicom2nifti
  - simpleitk
  - pandas
  - medpy

